### PR TITLE
OpenID Connect integration

### PR DESCRIPTION
**Pull request by assusdan**
There is request for SSO technologies support (see #74). One of SSO variants is OpenID Connect. So, i decided to implement such integration. 

This PR adds a lot of dependencies, so I may consider to rewrite some of used OIDC libraries in order to get rid of some deps.

### CODE REVIEW

**Review by decentral1se — COMMENTED** [review]
LGTM!

One question: does the `OidcProviderUri` include the realm? e.g. `https://mykeycloak.com/auth/realms/$MY-REALM/...` I think it does, in which case, great!

Hoping this can be merged at some point in the neat future as I'd love to test it out.

Thanks for the work!

**Comment by assusdan** [comment]
@decentral1se this MR is actually in precess of rewrite. I'm changing working with users a bit, for better support of multitenancy. Multiple OIDC providers will be also supported. I will ensure Keycloak setups work well, too.

However, this MR will not be merged until temperature in my city will lower, as I do not have air conditioning and its too hard to work right now.

**Comment by decentral1se** [comment]
solidarity @assusdan and thanks for the update, will be v happy to test / review your work! hope things will cool down soon...

**Comment by bouncepaw** [comment]
Is development still active?

**Pull request closed without merging**
