### PR TITLE
add 'reader' group

### PR DESCRIPTION
**Pull request by la-ninpre**
# the problem

mycorrhiza has **lock** feature, which disallows unauthenticated users to view the content. currently, all available user groups have write permission, which is not always applicable. i thought that creating a user and assigning it to `anon` group would give me an ability to create wiki that is accessible only by entering some credentials which could be shared. but it seems that `anon` users can't log in when the wiki is locked.

# quick & dirty solution

i propose the addition of `reader` group, it is essentially the same as `anon` but is allowed to log in and read pages if wiki is locked down. this might look like a bodge and in fact it is. the better solution would be to tweak the behaviour of `anon` group. if i understand it correctly, `anon` group is assigned by default to any user visiting the wiki, despite wiki being locked down or not. tell me if i'm wrong and feel free to close this pr.

### CODE REVIEW

**Comment by handlerug** [comment]
Doesn't seem to be a bodge to me. Looks like a nice way of moderating registrations too.

**Comment by bouncepaw** [comment]
I had this idea before, looks ok. Are you sure you got all places referring the user groups covered?

Will run a quick test tomorrow.

**Comment by la-ninpre** [comment]
hmm, i think it would be wise to change default group to `reader` when a new user gets registered.

**Comment by la-ninpre** [comment]
and also a list of readers could be added to `/user-list` page.

**Comment by bouncepaw** [comment]
> hmm, i think it would be wise to change default group to reader when a new user gets registered.

No it's not

**Comment by bouncepaw** [comment]
The whole point of registering is to be able to edit. That's a wiki after all

**Comment by la-ninpre** [comment]
ok

**Comment by la-ninpre** [comment]
> Are you sure you got all places referring the user groups covered?

about that... well, i'm pretty sure i got everything but it's not a bad idea to double-check.

**Comment by bouncepaw** [comment]
LGTM, thanks!

**Pull request merged**
