### PR TITLE
Create Dockerfile

### PR DESCRIPTION
**Pull request by bhartshorn**
If you want it :+1: 

Adds simple two-stage Dockerfile

Project looks pretty cool, giving it a run.

### CODE REVIEW

**Comment by DanInSpace104** [comment]
> Adds simple two-stage Dockerfile

@bhartshorn Thank you for contribution, Docker can be very useful! It is not critical, but your Dockerfile can't use auth system. Also, can you add some installation and run instructions into README?

**Comment by bhartshorn** [comment]
Sure, I can add some docs :+1:

@DanInSpace104 It took me a bit to figure out why 
> Dockerfile can't use auth system

Looks like a limitation in golang flags library? (I guess it stops parsing when it hits an unknown flag?) 

Options are:
- [ ] create an entrypoint script to wrap
- [ ] fix up the command line flags implementation so path can be positional (last argument) OR passed as a flag
- [ ] default PWD as wiki directory

Looks like the second option is difficult to do cleanly with the stdlib `flags`, would be much easier with a more feature-rich library. I'll add a wrapper script for now and it can be easily replaced in the future.

**Comment by bouncepaw** [comment]
Please note that branch 0.12 has been merged, you should change target branch of your pull request to 0.13.

Anyway, thanks for your interest. Looking forward to an awesome Dockerfile 👍.

**Comment by bouncepaw** [comment]
A month has passed. Seems like no one is interested anymore, I'm going to close this issue when 0.13 is released if no one picks this topic up.

**Comment by bhartshorn** [comment]
@bouncepaw Apologies, I'm not going to get around to wrapping this up. I'll go ahead and close now. Best of luck with mycorrhiza!

**Comment by DanInSpace104** [comment]
> I'll go ahead and close now. Best of luck with mycorrhiza!

Anyways, thank you @bhartshorn for your good intentions! :) Hope to see you again on mycorrhiza

**Pull request closed without merging**
